name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: main
          fetch-depth: 0

      - uses: actions/checkout@v4
        with:
          ref: pages
          path: pages

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Build
        run: |
          cd main
          ./build.sh
          entries=`find * -maxdepth 0 -type d`
          for directory in $entries; do
            rm -rf ../pages/$directory
            mkdir -p ../pages/$directory
            cp -r $directory/dist/* ../pages/$directory
          done
          commit_id=`git rev-parse HEAD`
          cd ../pages
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config user.name "$GITHUB_ACTOR"
          git add .
          git commit -am "pages from $commit_id"
          git push
